### ISSUE TITLE
祈愿记录云同步无法正常使用

### ISSUE THREAD

**Issue by smallg0at** [xunkong/xunkong#175]
### 问题描述

在进行任意记录备份菜单下的操作时，会进行一次查询云端状态操作，此时服务器会在较长时间后返回以下 Response 导致失败：
```
{
  "code": -1,
  "message": "An error occurred while saving the entity changes. See the inner exception for details.",
  "data": null
}
```

### 复现步骤

1. 查询（祈愿）记录数量

### 系统版本

Windows 11 Build 25188

### 寻空版本

1.1.7（商店版）

### 日志

（可能和此问题没有关系，正常情况下链接不会被中断）
```

[13:22:30.207] [INFO] 
寻空 1.1.7.0
08BCBC462BAC53A3F6F817461C21EA47
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.1.7.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[13:22:30.212] [EROR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel+<QueryWishlogInCloudAsync>d__54.QueryWishlogInCloudAsync
查询祈愿记录备份
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Xunkong.ApiClient.XunkongApiClient.CommonPostAsync[T](String url, Object value)
   at Xunkong.ApiClient.XunkongApiClient.GetWishlogLastItemFromCloudAsync(WishlogBackupRequest request)
   at Xunkong.Desktop.Services.XunkongApiService.GetWishlogBackupLastItemAsync(Int32 uid, IProgress`1 progress)
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.QueryWishlogInCloudAsync()
```

**Comment by Scighost** [comment]
有可能你的记录中出现了某些奇怪的东西，日志中是网络错误和 `code=-1` 没有关系。

**Comment by smallg0at** [comment]
> 有可能你的记录中出现了某些奇怪的东西，日志中是网络错误和 `code=-1` 没有关系。

我试着做了一下删除云端记录操作，结果发现删除也需要先查询云端状态，删除无法正常进行。

**Comment by Scighost** [comment]
不清楚你那发生了什么，我这一切正常，有需要可以把网址发给我，我帮你操作。
