### ISSUE TITLE
深境螺旋页面不显示

### ISSUE THREAD

**Issue by QAQosuy** [xunkong/xunkong#176]
### 问题描述

深境螺旋页面不显示，报错如下图

### 复现步骤

打开软件，点击深境螺旋，页面报错，刷新报错，显示空白

### 截图

![image](https://user-images.githubusercontent.com/41537133/187662763-85531b39-0072-48bf-b353-b808139ad948.png)

### 系统版本

Windows 10 专业版 21H2 19044.1889

### 寻空版本

1.1.7.0

### 日志

[18:56:51.436] [EROR] Xunkong.Desktop.Pages.SpiralAbyssPage.InitializeData
初始化深渊页面
System.ArgumentNullException: Value cannot be null. (Parameter 'json')
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Xunkong.Desktop.Services.HoyolabService.GetSpiralAbyssInfo(Int32 id)
   at Xunkong.Desktop.Pages.SpiralAbyssPage.InitializeData()

**Comment by Scighost** [comment]
数据库出现了错误，最新一期深渊的数据为 `null` ，把那条记录删掉就行。

**Comment by QAQosuy** [comment]
> 数据库出现错误，最新一期深渊的数据为`null`，把那条记录删掉就行了。

感谢，自己改了数据库🤣
![image](https://user-images.githubusercontent.com/41537133/188661287-a062da3d-1390-4895-a9a3-33e7cf3daa3b.png)
![image](https://user-images.githubusercontent.com/41537133/188661465-4924f200-a5f3-4985-9dfa-1a7a4649298a.png)
