### ISSUE TITLE
获取祈愿记录时无法正常启动代理

### ISSUE THREAD

**Issue by Desmond-H** [xunkong/xunkong#179]
### 问题描述

试图更新祈愿记录时弹出红色提示找不到文件，无法启动代理也无法获取祈愿记录，如截图所示。该问题从原神更新3.0版本、寻空更新1.1.5.0版本后一直存在，最新版本1.1.7.0中仍然无法正常获取祈愿记录

### 复现步骤

在祈愿记录界面选择 启动代理/增量更新/全量更新 均出现此问题，无法正常启动代理获取祈愿记录

### 截图

![image](https://user-images.githubusercontent.com/27613398/188276739-1d18414e-a248-4eb5-948b-eb12587e8282.png)

### 系统版本

Windows 10 2004

### 寻空版本

1.1.7.0

### 日志

[Uploading log_20220903_230504.txt…]()

[23:05:04.676] [INFO] 
寻空 侧载版 1.1.7.0
192AF03B937F0A8EEA5211B65AAD4816
"C:\Program Files\WindowsApps\Xunkong.Desktop.Package_1.1.7.0_x64__fyamk49073ha2\Xunkong.Desktop\Xunkong.Desktop.dll"

[23:05:04.677] [EROR] Xunkong.Desktop.Pages.MainPage+<SignInAsync>d__26.SignInAsync
签到
System.FormatException: 1 is not a valid value for Boolean.
 ---> System.FormatException: String '1' was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.Boolean.Parse(String value)
   at System.ComponentModel.BooleanConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BooleanConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFromString(String text)
   at Xunkong.Desktop.Helpers.UserSetting.GetValue[T](String key, T defaultValue, Boolean throwError)
   at Xunkong.Desktop.Pages.MainPage.SignInAsync()

[23:05:05.164] [EROR] Xunkong.Desktop.Pages.MainPage+<<RefreshAllAcountAsync>b__25_0>d.RefreshAllAcountAsync
刷新所有账号信息
Xunkong.Hoyolab.HoyolabException: 登录失效，请重新登录 (-100)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie)
   at Xunkong.Desktop.Services.HoyolabService.UpdateAllAccountsAsync()
   at Xunkong.Desktop.Pages.MainPage.<RefreshAllAcountAsync>b__25_0()

[23:05:11.896] [EROR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel+<StartProxyAsync>d__49.StartProxyAsync
启动代理
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'reg' with working directory 'C:\Program Files\WindowsApps\Xunkong.Desktop.Package_1.1.7.0_x64__fyamk49073ha2\Xunkong.Desktop'. 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Xunkong.Desktop.Services.ProxyService.SetSystemProxy(Boolean enable)
   at Xunkong.Desktop.Services.ProxyService.StartProxyAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.ShowProxyDialogAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.StartProxyAsync()

[23:05:23.304] [EROR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel+<StartProxyAsync>d__49.StartProxyAsync
启动代理
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'reg' with working directory 'C:\Program Files\WindowsApps\Xunkong.Desktop.Package_1.1.7.0_x64__fyamk49073ha2\Xunkong.Desktop'. 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Xunkong.Desktop.Services.ProxyService.SetSystemProxy(Boolean enable)
   at Xunkong.Desktop.Services.ProxyService.StartProxyAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.ShowProxyDialogAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.StartProxyAsync()

[23:06:07.656] [EROR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel+<StartProxyAsync>d__49.StartProxyAsync
启动代理
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'reg' with working directory 'C:\Program Files\WindowsApps\Xunkong.Desktop.Package_1.1.7.0_x64__fyamk49073ha2\Xunkong.Desktop'. 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Xunkong.Desktop.Services.ProxyService.SetSystemProxy(Boolean enable)
   at Xunkong.Desktop.Services.ProxyService.StartProxyAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.ShowProxyDialogAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.StartProxyAsync()

[23:06:30.374] [EROR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel+<StartProxyAsync>d__49.StartProxyAsync
启动代理
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'reg' with working directory 'C:\Program Files\WindowsApps\Xunkong.Desktop.Package_1.1.7.0_x64__fyamk49073ha2\Xunkong.Desktop'. 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Xunkong.Desktop.Services.ProxyService.SetSystemProxy(Boolean enable)
   at Xunkong.Desktop.Services.ProxyService.StartProxyAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.ShowProxyDialogAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.StartProxyAsync()

**Comment by Scighost** [comment]
系统环境变量问题，请自行搜索解决。

**Comment by Desmond-H** [comment]
我尝试了网上的教程，但没有作用。是否可以给个关键词应该搜索调整什么变量呢？
