### ISSUE TITLE
xunkong大部分功能不能正常使用

### ISSUE THREAD

**Issue by TohoKabo** [xunkong/xunkong#188]
### 问题描述

祈愿 图鉴 角色信息都不正常提示初始化

### 复现步骤

打开左侧菜单选择就会出现

### 截图

![image](https://user-images.githubusercontent.com/112839899/189379611-2b8eac40-f300-4ab9-a6f0-69204f36c7a0.png)

### 系统版本

win11 22h2

### 寻空版本

1.2.0

### 日志

[22:51:15.683] [INFO] 
寻空 1.2.0.0
8296490D514B917456D4605ADE43CF26
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.2.0.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[22:51:15.684] [EROR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.LoadWishlog
加载祈愿数据
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method61(Closure , Object , Object )
   at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.LoadWishlog(Boolean ignoreWishlogStats)

[22:51:16.947] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage+<InitializeDataAsync>d__24.InitializeDataAsync
初始化角色信息页面
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method61(Closure , Object , Object )
   at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Xunkong.Desktop.Pages.CharacterInfoPage.InitializeDataAsync()

[22:51:20.450] [EROR] Xunkong.Desktop.Pages.MainPage.GetGenshinData
获取原神数据
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Xunkong.ApiClient.XunkongApiClient.CommonGetAsync[T](String url)
   at Xunkong.ApiClient.XunkongApiClient.GetAllGenshinDataAsync()
   at Xunkong.Desktop.Services.XunkongApiService.GetAllGenshinDataFromServerAsync()
   at Xunkong.Desktop.Pages.MainPage.<GetGenshinData>b__24_0()

[22:51:23.216] [EROR] Xunkong.Desktop.Pages.CharacterWikiPage.InitializePage
初始化角色图鉴页面
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method61(Closure , Object , Object )
   at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
   at Xunkong.Desktop.Pages.CharacterWikiPage.InitializePage()

[22:51:25.897] [EROR] Xunkong.Desktop.Pages.WeaponWikiPage.InitiliazePage
初始化武器图鉴页面
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Xunkong.Desktop.Pages.WeaponWikiPage.WeaponWikiPage_obj1_Bindings.Update_SelectedWeapon_WeaponInfo_Skills(List`1 obj, Int32 phase)
   at Xunkong.Desktop.Pages.WeaponWikiPage.WeaponWikiPage_obj1_Bindings.Update_SelectedWeapon_WeaponInfo(WeaponInfo obj, Int32 phase)
   at Xunkong.Desktop.Pages.WeaponWikiPage.WeaponWikiPage_obj1_Bindings.Update_SelectedWeapon(PM_WeaponWiki_WeaponInfo obj, Int32 phase)
   at Xunkong.Desktop.Pages.WeaponWikiPage.WeaponWikiPage_obj1_Bindings.WeaponWikiPage_obj1_BindingsTracking.PropertyChanged_(Object sender, PropertyChangedEventArgs e)
   at Xunkong.Desktop.Pages.WeaponWikiPage.set_SelectedWeapon(PM_WeaponWiki_WeaponInfo value)
   at Xunkong.Desktop.Pages.WeaponWikiPage.InitiliazePage()

**Comment by TohoKabo** [comment]
打不开，刚才1.17还正常

**Comment by Scighost** [comment]
[GenshinData.zip](https://github.com/xunkong/xunkong/files/9536541/GenshinData.zip)

下载上面那个压缩包解压后，覆盖文件 `我的文档\Xunkong\Database\GenshinData.db`。
这只是暂时的办法，无法连接到 `api.xunkong.cc` 的话，你还是无法获取到以后的数据更新。
