### ISSUE TITLE
寻空1.2.1.0 使用代理获取祈愿记录后闪退

### ISSUE THREAD

**Issue by Smallwhite777** [xunkong/xunkong#208]
### 问题描述

启动代理之后去游戏内查看历史记录，会弹出通知提示获取成功，然后寻空就闪退了，重启寻空之后可以正常使用增量更新和全量更新

### 复现步骤

祈愿记录-启动代理-历史记录-弹出通知提示获取成功-寻空闪退

### 系统版本

Windows 11 专业版 21H2

### 寻空版本

1.2.1.0

### 日志

[14:37:23.156] [INFO] 
寻空 侧载版 1.2.1.0
4CB684FDD8D8131EF2A33756DBA4F1D9
"C:\Program Files\WindowsApps\Xunkong.Desktop.Package_1.2.1.0_x64__fyamk49073ha2\Xunkong.Desktop\Xunkong.Desktop.dll"

[14:37:23.157] [EROR] Xunkong.Desktop.Pages.MainPage.RefreshAllAcount
刷新所有账号信息
Xunkong.Hoyolab.HoyolabException: 登录失效，请重新登录 (-100)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie)
   at Xunkong.Desktop.Services.HoyolabService.UpdateAllAccountsAsync()
   at Xunkong.Desktop.Pages.MainPage.<RefreshAllAcount>b__25_0()

[14:38:06.110] [EROR] Xunkong.Desktop.App.App_UnhandledException
崩溃了
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.DataTransfer.IClipboardStaticsMethods.Flush(IObjectReference _obj)
   at Windows.ApplicationModel.DataTransfer.Clipboard.Flush()
   at Xunkong.Desktop.Helpers.ClipboardHelper.SetText(String value)
   at Xunkong.Desktop.Pages.SettingPage.CopyDevelopersMail()
   at CommunityToolkit.Mvvm.Input.RelayCommand.Execute(Object parameter)
   at ABI.System.Windows.Input.ICommand.Vftbl.Do_Abi_Execute_3(IntPtr thisPtr, IntPtr parameter)

**Comment by Scighost** [comment]
剪贴板被占用或者复制操作被拦截。
获取记录时直接选择**从缓存文件**，不要使用代理。
