### ISSUE TITLE
第一次使用成功启用代理但是重新打开祈愿记录页面没有拉取到地址

### ISSUE THREAD

**Issue by magicdolls** [xunkong/xunkong#212]
### 问题描述

第一次使用，按照教程成功安装并且代理启动成功，打开游戏重新打开祈愿记录没获得任何网址无法增量更新。

### 复现步骤

启动寻空，打开祈愿记录，启动代理（显示绿字启动成功），切回游戏重新打开祈愿记录，之后没有获取网址成功，剪贴板也没网址。

### 截图

无

### 系统版本

win10 教育版 10.0.19042

### 寻空版本

1.2.1.0

### 日志

[11:12:29.128] [INFO] 
寻空 1.2.1.0
202BDF4F2ABA8BC7D4DBEEACB53B614E
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.2.1.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[11:12:29.128] [EROR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel+<GetWishlogFromCacheFileAsync>d__49.GetWishlogFromCacheFileAsync
获取祈愿记录
Xunkong.Core.XunkongException: 没有找到 YuanShen.exe，请前往设置页面指定路径。
   at Xunkong.Desktop.Services.InvokeService.GetGameExePathAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.GetWishlogFromCacheFileAsync()

[11:13:23.111] [EROR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel+<GetWishlogFromCacheFileAsync>d__49.GetWishlogFromCacheFileAsync
获取祈愿记录
Xunkong.Core.XunkongException: 没有找到 YuanShen.exe，请前往设置页面指定路径。
   at Xunkong.Desktop.Services.InvokeService.GetGameExePathAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.GetWishlogFromCacheFileAsync()

[11:14:50.214] [EROR] Xunkong.Desktop.Pages.HomePage+<GetNotificationContentAsync>d__25.GetNotificationContentAsync
主页通知栏内容
System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (api.xunkong.cc:443)
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Xunkong.ApiClient.XunkongApiClient.CommonGetAsync[T](String url)
   at Xunkong.ApiClient.XunkongApiClient.GetInfoBarContentListAsync(ChannelType channel, Version version)
   at Xunkong.Desktop.Services.XunkongApiService.GetInfoBarContentListAsync()
   at Xunkong.Desktop.Pages.HomePage.GetNotificationContentAsync()

[11:14:52.621] [EROR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel+<GetWishlogFromCacheFileAsync>d__49.GetWishlogFromCacheFileAsync
获取祈愿记录
Xunkong.Core.XunkongException: 没有找到 YuanShen.exe，请前往设置页面指定路径。
   at Xunkong.Desktop.Services.InvokeService.GetGameExePathAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.GetWishlogFromCacheFileAsync()

[11:15:19.979] [EROR] Xunkong.Desktop.Pages.SettingPage+<UpdateGenshinDataAsync>d__39.UpdateGenshinDataAsync
手动更新原神数据
System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (api.xunkong.cc:443)
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Xunkong.ApiClient.XunkongApiClient.CommonGetAsync[T](String url)
   at Xunkong.ApiClient.XunkongApiClient.GetAllGenshinDataAsync()
   at Xunkong.Desktop.Services.XunkongApiService.GetAllGenshinDataFromServerAsync()
   at Xunkong.Desktop.Pages.SettingPage.UpdateGenshinDataAsync()

[11:17:44.430] [EROR] Xunkong.Desktop.Pages.HomePage+<GetNotificationContentAsync>d__25.GetNotificationContentAsync
主页通知栏内容
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Xunkong.ApiClient.XunkongApiClient.CommonGetAsync[T](String url)
   at Xunkong.ApiClient.XunkongApiClient.GetInfoBarContentListAsync(ChannelType channel, Version version)
   at Xunkong.Desktop.Services.XunkongApiService.GetInfoBarContentListAsync()
   at Xunkong.Desktop.Pages.HomePage.GetNotificationContentAsync()

[11:18:33.145] [EROR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel+<GetWishlogFromCacheFileAsync>d__49.GetWishlogFromCacheFileAsync
获取祈愿记录
Xunkong.Core.XunkongException: 没有找到 YuanShen.exe，请前往设置页面指定路径。
   at Xunkong.Desktop.Services.InvokeService.GetGameExePathAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.GetWishlogFromCacheFileAsync()

[11:20:42.803] [EROR] Xunkong.Desktop.ViewModels.WishlogSummaryViewModel+<GetWishlogFromCacheFileAsync>d__49.GetWishlogFromCacheFileAsync
获取祈愿记录
Xunkong.Core.XunkongException: 没有找到 YuanShen.exe，请前往设置页面指定路径。
   at Xunkong.Desktop.Services.InvokeService.GetGameExePathAsync()
   at Xunkong.Desktop.ViewModels.WishlogSummaryViewModel.GetWishlogFromCacheFileAsync()

### 备注

想使用缓存更新但是游戏的exe文件是launcher.exe不是内设的yuanshen或者genshin没法设置游戏

**Comment by Scighost** [comment]
设置页面 启动游戏 修改路径

**Comment by magicdolls** [comment]
> 他要求必须文件名是yuanshen.exe或者genshinimpact.exe，我打开安装文件夹之后游戏的exe文件是launcher.exe，设置的时候显示文件名不对无法设置

**Comment by magicdolls** [comment]
> 设置页面 启动游戏 修改路径

解决了，外面是launcher.exe没法设置，文件夹里还有个Genshin Impact Game，里面才是yuanshen.exe
