### ISSUE TITLE
“从缓存文件”无法使用

### ISSUE THREAD

**Issue by xiaoouxiaoou** [xunkong/xunkong#213]
### 问题描述

之前可正常使用该功能，但是现在点击“从缓存文件”按钮后出现authkey timeout (-101)

### 复现步骤

另外，启动代理后无法获得祈愿记录

### 系统版本

Windows 10 1909

### 寻空版本

1.2.1.0

### 日志

[13:39:48.663] [INFO] 
寻空 侧载版 1.2.1.0
91D0BE98335D50B0C28211B784BAB7A5
"C:\Program Files\WindowsApps\Xunkong.Desktop.Package_1.2.1.0_x64__fyamk49073ha2\Xunkong.Desktop\Xunkong.Desktop.dll"

[13:39:48.666] [EROR] Xunkong.Desktop.Pages.MainPage.SignInAllAccount
签到 MIKESI
Xunkong.Hoyolab.HoyolabException: 账号 MIKESI 受到风控限制，请前往米游社手动签到。 (375)
   at Xunkong.Hoyolab.HoyolabClient.SignInAsync(GenshinRoleInfo role, Boolean skipCheckWhetherHaveSignedIn, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.SignInAsync(GenshinRoleInfo role)
   at Xunkong.Desktop.Pages.MainPage.<SignInAllAccount>b__26_0()

**Comment by Nikaple** [comment]
可参考我的解决方案试试：https://github.com/xunkong/xunkong/issues/220#issuecomment-1383074044
