### ISSUE TITLE
管理记录/卡池历史页面返回时崩溃

### ISSUE THREAD

**Issue by Fachep** [xunkong/xunkong#244]
### 问题描述

在祈愿记录 -> 管理记录/卡池历史页面点击左上角返回按钮崩溃

### 复现步骤

祈愿记录-管理记录/卡池历史-返回按钮

### 系统版本

Windows 11 22H2（22H1时也有此问题）

### 寻空版本

1.2.2.0

### 日志

```
[18:14:32.620] [INFO] 
寻空 1.2.2.0
D8D6345B0B33978C58AB90262D039D0B
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.2.2.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[18:14:32.621] [EROR] Xunkong.Desktop.App.App_UnhandledException
崩溃了
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunkong.Desktop.Pages.MainPage._NavigationView_ItemInvoked(NavigationView sender, NavigationViewItemInvokedEventArgs args)
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.INavigationViewMethods.set_SelectedItem(IObjectReference _obj, Object value)
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)
```

**Comment by pbxs666** [comment]
刚测试了，我这边是有概率会未响应，没有直接崩溃
