### ISSUE TITLE
添加网页闪退

### ISSUE THREAD

**Issue by afasdaws** [xunkong/xunkong#297]
### 问题描述

添加网页快捷方式，点添加时候闪退

### 复现步骤

设置→网页快捷方式→添加→闪退

### 系统版本

Windows 11 22H2 22621.819

### 寻空版本

1.2.3.0

### 日志

[10:04:32.711] [INFO] 
寻空 1.2.3.0
0ACD80FCB619CE1F6BF314EDD33FE028
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.2.3.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[10:04:32.713] [EROR] Xunkong.Desktop.App.App_UnhandledException
崩溃了
System.ArgumentException: Value does not fall within the expected range.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Markup.IXamlBindingHelperStaticsMethods.ConvertValue(IObjectReference _obj, Type type, Object value)
   at Xunkong.Desktop.Pages.SettingPage.SettingPage_obj22_Bindings.Update_Icon(String obj, Int32 phase) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\obj\x64\Release\net7.0-windows10.0.22621.0\win10-x64\Pages\SettingPage.g.cs:line 269
   at Xunkong.Desktop.Pages.SettingPage.SettingPage_obj22_Bindings.Update_(WebToolItem obj, Int32 phase) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\obj\x64\Release\net7.0-windows10.0.22621.0\win10-x64\Pages\SettingPage.g.cs:line 258
   at ABI.Microsoft.UI.Xaml.Markup.IDataTemplateComponent.Do_Abi_ProcessBindings_1(IntPtr thisPtr, IntPtr item, Int32 itemIndex, Int32 phase, Int32* nextPhase)

**Comment by ch948643565** [comment]
啊，我还想提，看到你和三天前也有个人提了，大佬说复现成功，原因不明，开摆

**Comment by Waximell** [comment]
同beta通道，22623.819，有此问题，稳定复现（指每次点添加必定闪退），希望尽快解决

**Comment by ch948643565** [comment]
您的邮件已经收到，我会尽快查看。

**Comment by Scighost** [comment]
更新到 1.2.4
