### ISSUE TITLE
无法添加帐号。

### ISSUE THREAD

**Issue by cdl5945** [xunkong/xunkong#315]
### 问题描述

不管是网页登陆还是填写cookie都不行。提示获取不到cookie_token。后来我仔细查看了下发现PC端米游社网页登陆给的cookie不包含token字段了。

### 复现步骤

使用寻空的网页登陆。点√后提示获取不到cookie token
使用edge的无痕模式登陆米游社，点击获取书签提示没有找到 cookie_token 和 account_id，请重新登录
咨询别的网友后给了个方法，说是登陆米游社后再点击米哈游通行证帐号管理网页，登陆后利用F12控制台输入
var cookie=document.cookie;var ask=confirm('Cookie:'+cookie+'\n\nDo you want to copy the cookie to the clipboard?');if(ask==true){copy(cookie);msg=cookie}else{msg='Cancel'}
来获取cookie。可是获取的cookie还是没有token字段，但是发给Q群的原神机器人后可以解析出token。

### 系统版本

win10 22H2

### 寻空版本

1.2.3.0

### 日志

[22:38:07.327] [INFO] 
寻空 1.2.3.0
16A6718F3E4BAFA9985940AEFD8498EA
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.2.3.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[22:38:07.328] [EROR] Xunkong.Desktop.Pages.MainPage+<<NavigateToLoginPage>b__30_0>d.NavigateToLoginPage
导航到米游社登录页面
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.<NavigateToLoginPage>b__30_0(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 461

[22:38:16.223] [EROR] Xunkong.Desktop.Pages.MainPage+<<NavigateToLoginPage>b__30_0>d.NavigateToLoginPage
导航到米游社登录页面
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.<NavigateToLoginPage>b__30_0(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 461

[22:38:28.736] [EROR] Xunkong.Desktop.Pages.MainPage+<<NavigateToLoginPage>b__30_0>d.NavigateToLoginPage
导航到米游社登录页面
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.<NavigateToLoginPage>b__30_0(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 461

[22:46:52.644] [EROR] Xunkong.Desktop.Pages.MainPage+<AddCookieAsync>d__31.AddCookieAsync
获取账号信息
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.AddCookieAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 526

[22:48:07.268] [EROR] Xunkong.Desktop.Pages.MainPage+<AddCookieAsync>d__31.AddCookieAsync
获取账号信息
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.AddCookieAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 526

[22:48:15.579] [EROR] Xunkong.Desktop.Pages.MainPage+<<NavigateToLoginPage>b__30_0>d.NavigateToLoginPage
导航到米游社登录页面
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.<NavigateToLoginPage>b__30_0(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 461

[23:02:56.433] [EROR] Xunkong.Desktop.Pages.MainPage+<<NavigateToLoginPage>b__30_0>d.NavigateToLoginPage
导航到米游社登录页面
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.<NavigateToLoginPage>b__30_0(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 461

[23:05:48.450] [EROR] Xunkong.Desktop.Pages.MainPage+<<NavigateToLoginPage>b__30_0>d.NavigateToLoginPage
导航到米游社登录页面
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.<NavigateToLoginPage>b__30_0(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 461

[23:36:11.897] [EROR] Xunkong.Desktop.Pages.MainPage+<AddCookieAsync>d__31.AddCookieAsync
获取账号信息
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.AddCookieAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 526

[23:39:34.017] [EROR] Xunkong.Desktop.Pages.MainPage+<AddCookieAsync>d__31.AddCookieAsync
获取账号信息
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.AddCookieAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 526

[23:40:21.027] [EROR] Xunkong.Desktop.Pages.MainPage+<AddCookieAsync>d__31.AddCookieAsync
获取账号信息
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.AddCookieAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 526

[23:44:32.803] [EROR] Xunkong.Desktop.Pages.MainPage+<<NavigateToLoginPage>b__30_0>d.NavigateToLoginPage
导航到米游社登录页面
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.<NavigateToLoginPage>b__30_0(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 461

**Comment by fnyfree** [comment]
同样问题，解决能踹一脚吗（_(:з)∠)_

**Comment by shuhang628** [comment]
我也是这样！！！！！！！！

**Comment by shuhang628** [comment]
解决可以t一下吗 谢谢

**Comment by BxnIceLemon** [comment]
碰到了一样的问题，希望尽快修复

**Comment by Scighost** [comment]
米游社网页版已升级，获取不到 `cookie_token` 。
最近没空，无法承诺更新时间。

**Comment by sodedad** [comment]
w我也是怎么办啊

**Comment by zjxian** [comment]
![image](https://user-images.githubusercontent.com/11209426/204073287-98328fe8-e710-4936-897e-cece4bf4f41f.png)
推测是改成了 ltoken 和 ltuid

**Comment by scwunai** [comment]
暂时可以F12 网络里ys/下拷贝全部的cookie内容，然后把account_mid_v2改成account_id，ltoken_v2改成cookie_token然后复制全部内容丢到输入cookie的框里，应该能暂时解决问题

**Comment by cdl5945** [comment]
> 暂时可以F12 网络里ys/下拷贝全部的cookie内容，然后把account_mid_v2改成account_id，ltoken_v2改成cookie_token然后复制全部内容丢到输入cookie的框里，应该能暂时解决问题 但是实测会有部分功能有问题

试了下用上周发给机器人的还能读取到token的cookie，成功添加帐号了，目前只有实时便签和旅行札记功能无法使用，其它的都可以。现在就等作者更新了。

**Comment by lizhengyi3003** [comment]
我也有这个问题，求解决

**Comment by zjxian** [comment]
> 暂时可以F12 网络里ys/下拷贝全部的cookie内容，然后把account_mid_v2改成account_id，ltoken_v2改成cookie_token然后复制全部内容丢到输入cookie的框里，应该能暂时解决问题 但是实测会有部分功能有问题

实测有效

**Comment by lizhengyi3003** [comment]
是吗，我试一下，好的，谢谢！
&nbsp;


飞船
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月27日(星期天) 上午10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xunkong/xunkong] 无法添加帐号。 (Issue #315)





  
暂时可以F12 网络里ys/下拷贝全部的cookie内容，然后把account_mid_v2改成account_id，ltoken_v2改成cookie_token然后复制全部内容丢到输入cookie的框里，应该能暂时解决问题 但是实测会有部分功能有问题
  
实测有效

**Comment by cdl5945** [comment]
暂时解决了。我是利用隔壁的胡桃工具箱获取的cookie，然后复制后填入寻空的。所有功能都可以正常使用，每日便签和旅行札记都能正常显示。

**Comment by fivefirex** [comment]
~~嘿，还真灵~~

**Comment by Scighost** [comment]
更新到 1.2.4
