### ISSUE TITLE
你的标题

### ISSUE THREAD

**Issue by rugal934026411** [xunkong/xunkong#327]
### 问题描述

无法添加账号

### 复现步骤

正常流程不发添加账号

### 截图

![1](https://user-images.githubusercontent.com/53652104/204678193-09fa1fa7-402b-422c-9c41-dab74260c8b0.png)

### 系统版本

win10 20H2

### 寻空版本

1.2.3.0

### 日志

[08:27:44.591] [INFO] 
寻空 1.2.3.0
A9E25E5B73F581EC2488ECA55883086F
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.2.3.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[08:27:44.592] [EROR] Xunkong.Desktop.Pages.MainPage+<<NavigateToLoginPage>b__30_0>d.NavigateToLoginPage
导航到米游社登录页面
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.<NavigateToLoginPage>b__30_0(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 461

[08:28:26.347] [EROR] Xunkong.Desktop.Pages.MainPage+<<NavigateToLoginPage>b__30_0>d.NavigateToLoginPage
导航到米游社登录页面
System.ArgumentException: Cookie does not contain "account_id" or "cookie_token".
   at Xunkong.Hoyolab.HoyolabClient.GetHoyolabUserInfoAsync(String cookie, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 75
   at Xunkong.Desktop.Pages.MainPage.<NavigateToLoginPage>b__30_0(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 461

**Comment by fivefirex** [comment]
请参见置顶 issue #315。
