### ISSUE TITLE
管理员模式下运行寻空无法选择本地文件

### ISSUE THREAD

**Issue by XLBHCF** [xunkong/xunkong#369]
### 问题描述

![图片](https://user-images.githubusercontent.com/108862760/212953855-8a5ea8ae-e5f0-4e79-b9e0-66fc3f8faae7.png)

### 复现步骤

在开始菜单右键 以管理员身份运行 后，启动游戏提示无法找到游戏文件
![图片](https://user-images.githubusercontent.com/108862760/212954172-bf07774e-ebff-45fe-acad-7a149803af45.png)
点击 选择文件 按键后出现如图问题

### 系统版本

Windows 11 家庭中文版 22H2

### 寻空版本

1.3.0.0

### 日志

[23:55:20.326] [EROR] Xunkong.Desktop.Pages.TravelNotesPage+<InitializeDataAsync>d__37.InitializeDataAsync
初始化旅行札记页面
Xunkong.Hoyolab.HoyolabException: 未登录 (-100)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetTravelNotesSummaryAsync(GenshinRoleInfo role, Int32 month, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetTravelNotesSummaryAsync(GenshinRoleInfo role, Int32 month) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 355
   at Xunkong.Desktop.Pages.TravelNotesPage.InitializeDataAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\TravelNotesPage.xaml.cs:line 149

[23:56:13.832] [EROR] Xunkong.Desktop.Services.GameAccountService+<StartGameAsync>d__15.StartGameAsync
启动游戏
Xunkong.Core.XunkongException: 没有找到CN的游戏文件，请在设置页面指定路径。
   at Xunkong.Desktop.Services.GameAccountService.GetGameExePath(Int32 server) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\GameAccountService.cs:line 193
   at Xunkong.Desktop.Services.GameAccountService.StartGameAsync(Int32 server, Boolean sendInAppNotification) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\GameAccountService.cs:line 260

[23:56:17.243] [EROR] Xunkong.Desktop.Pages.SettingPage+<ChangeGameExePathAsync>d__34.ChangeGameExePathAsync
设置游戏 exe 文件路径
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Xunkong.Desktop.Pages.SettingPage.ChangeGameExePathAsync(String server) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\SettingPage.xaml.cs:line 365

[00:19:07.222] [EROR] Xunkong.Desktop.Pages.SettingPage+<ChangeGameExePathAsync>d__34.ChangeGameExePathAsync
设置游戏 exe 文件路径
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Xunkong.Desktop.Pages.SettingPage.ChangeGameExePathAsync(String server) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\SettingPage.xaml.cs:line 365

[00:19:21.096] [EROR] Xunkong.Desktop.Pages.SettingPage+<ChangeGameExePathAsync>d__34.ChangeGameExePathAsync
设置游戏 exe 文件路径
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Xunkong.Desktop.Pages.SettingPage.ChangeGameExePathAsync(String server) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\SettingPage.xaml.cs:line 365

[00:19:23.227] [EROR] Xunkong.Desktop.Pages.SettingPage+<ChangeGameExePathAsync>d__34.ChangeGameExePathAsync
设置游戏 exe 文件路径
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Xunkong.Desktop.Pages.SettingPage.ChangeGameExePathAsync(String server) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\SettingPage.xaml.cs:line 365

[00:19:29.764] [EROR] Xunkong.Desktop.Pages.SettingPage+<ChangeGameExePathAsync>d__34.ChangeGameExePathAsync
设置游戏 exe 文件路径
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Xunkong.Desktop.Pages.SettingPage.ChangeGameExePathAsync(String server) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\SettingPage.xaml.cs:line 365

[00:20:27.823] [EROR] Xunkong.Desktop.Services.GameAccountService+<StartGameAsync>d__15.StartGameAsync
启动游戏
Xunkong.Core.XunkongException: 没有找到CN的游戏文件，请在设置页面指定路径。
   at Xunkong.Desktop.Services.GameAccountService.GetGameExePath(Int32 server) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\GameAccountService.cs:line 193
   at Xunkong.Desktop.Services.GameAccountService.StartGameAsync(Int32 server, Boolean sendInAppNotification) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\GameAccountService.cs:line 260

[00:20:44.607] [EROR] Xunkong.Desktop.Services.GameAccountService+<StartGameAsync>d__15.StartGameAsync
启动游戏
Xunkong.Core.XunkongException: 没有找到CN的游戏文件，请在设置页面指定路径。
   at Xunkong.Desktop.Services.GameAccountService.GetGameExePath(Int32 server) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\GameAccountService.cs:line 193
   at Xunkong.Desktop.Services.GameAccountService.StartGameAsync(Int32 server, Boolean sendInAppNotification) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\GameAccountService.cs:line 260

**Comment by Scighost** [comment]
参考 https://github.com/xunkong/xunkong/issues/291#issuecomment-1317042123
“键”的内容如下：

官服游戏路径
GameExePathCN

国际服游戏路径
GameExePathGlobal

云原神游戏路径
GameExePathCNCloud
