### ISSUE TITLE
实时便笺验证账号时出现未登录

### ISSUE THREAD

**Issue by Xuan0cheng** [xunkong/xunkong#410]
### 问题描述

如图，验证账号时出现提示登录，但按提示登录后仍是该状况，删除cookie重新添加也未解决。

### 复现步骤

点击验证账号，出现未登录，按提示登录后仍提示未登录

### 截图

![QQ截图20230211083857](https://user-images.githubusercontent.com/40588325/218227313-e859b8c5-43c7-47fd-8ffa-903029fb591f.png)

### 系统版本

Windows 11 22H2 22621.1194

### 寻空版本

1.3.2

### 日志

[08:24:31.869] [INFO] 
寻空 1.3.2.0
13DF34EAA8B775AA68FCCA1EF86C3B0F
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.3.2.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll" RefreshTile

[08:24:31.870] [EROR] Xunkong.Desktop.Services.InvokeService+<RefreshDailyNoteTilesAsync>d__0.RefreshDailyNoteTilesAsync
刷新磁贴 - Uid 178647169
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetDailyNoteAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetDailyNoteAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 348
   at Xunkong.Desktop.Services.InvokeService.RefreshDailyNoteTilesAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\InvokeService.cs:line 31

**Comment by Xuan0cheng** [comment]
可能与 #405 是同类问题？

**Comment by Xuan0cheng** [comment]
#395 大概是重复issue？
