### ISSUE TITLE
无法固定磁贴到开始菜单: 'Microsoft.Win32.TaskScheduler.TaskService' threw an exception

### ISSUE THREAD

**Issue by Patrick-Ze** [xunkong/xunkong#422]
### 问题描述

尝试固定磁贴到开始菜单时抛出异常：
`'Microsoft.Win32.TaskScheduler.TaskService' threw an exception`
通过“主页——实时便签”和左上角的账号列表固定磁贴时都会有这个问题

### 复现步骤

点击“固定到开始屏幕”

### 截图

![image](https://user-images.githubusercontent.com/19711799/221905359-ca471be4-ada8-419d-983c-6f00ab736819.png)

### 系统版本

Windows 10 21H2 (19044.2486)

### 寻空版本

1.3.3.0

### 日志

```log

[23:46:26.339] [INFO] 
寻空 侧载版 1.3.3.0
FC5FC16CBDA3776476B4E10D7B7087B8
"C:\Program Files\WindowsApps\Xunkong.Desktop.Package_1.3.3.0_x64__fyamk49073ha2\Xunkong.Desktop\Xunkong.Desktop.dll"

[23:46:26.340] [EROR] Xunkong.Desktop.Controls.DailyNoteCard+<PinToStartMenuAsync>d__9.PinToStartMenuAsync
固定磁贴到开始菜单
System.TypeInitializationException: The type initializer for 'Microsoft.Win32.TaskScheduler.TaskService' threw an exception.
 ---> System.NotSupportedException: Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more information.
   at Microsoft.Win32.TaskScheduler.TaskService.Connect()
   at Microsoft.Win32.TaskScheduler.TaskService.get_Instance()
   at Microsoft.Win32.TaskScheduler.TaskService..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Win32.TaskScheduler.TaskService.get_Instance()
   at Xunkong.Desktop.Services.TaskSchedulerService.RegisterForRefreshTile(Boolean enable) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\TaskSchedulerService.cs:line 71
   at Xunkong.Desktop.Controls.DailyNoteCard.PinToStartMenuAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Controls\DailyNoteCard.xaml.cs:line 111

[23:46:53.616] [EROR] Xunkong.Desktop.Controls.DailyNoteCard+<PinToStartMenuAsync>d__9.PinToStartMenuAsync
固定磁贴到开始菜单
System.TypeInitializationException: The type initializer for 'Microsoft.Win32.TaskScheduler.TaskService' threw an exception.
 ---> System.NotSupportedException: Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more information.
   at Microsoft.Win32.TaskScheduler.TaskService.Connect()
   at Microsoft.Win32.TaskScheduler.TaskService.get_Instance()
   at Microsoft.Win32.TaskScheduler.TaskService..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Win32.TaskScheduler.TaskService.get_Instance()
   at Xunkong.Desktop.Services.TaskSchedulerService.RegisterForRefreshTile(Boolean enable) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\TaskSchedulerService.cs:line 71
   at Xunkong.Desktop.Controls.DailyNoteCard.PinToStartMenuAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Controls\DailyNoteCard.xaml.cs:line 111
```

**Comment by Scighost** [comment]
应该是剪裁发布时裁掉了需要的东西，固定到磁贴是成功的，注册刷新磁贴的任务时失败了。
麻烦尝试安装1.3.2版本对比一下。

**Comment by Patrick-Ze** [comment]
我降级后试了一下，1.3.2没有问题。
