### ISSUE TITLE
旅行札记出现 提交参数有误(-2) 报错

### ISSUE THREAD

**Issue by BeiChenPorarisu** [xunkong/xunkong#424]
### 问题描述

rt，旅行札记出现 提交参数有误(-2) 报错，且以前保存的数据不显示，但能导出。

### 复现步骤

登录账户后，点击旅行札记，出现报错。

### 截图

![屏幕截图(86)](https://user-images.githubusercontent.com/30619226/221931188-67d42e66-8da4-4876-9f84-f9002cc8ba28.png)

### 系统版本

Windows 11 25300.1000

### 寻空版本

1.3.3.0

### 日志

[01:17:54.804] [EROR] Xunkong.Desktop.Pages.TravelNotesPage+<InitializeDataAsync>d__37.InitializeDataAsync
初始化旅行札记页面
Xunkong.Hoyolab.HoyolabException: 提交参数有误 (-2)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetTravelNotesSummaryAsync(GenshinRoleInfo role, Int32 month, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetTravelNotesSummaryAsync(GenshinRoleInfo role, Int32 month) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 358
   at Xunkong.Desktop.Pages.TravelNotesPage.InitializeDataAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\TravelNotesPage.xaml.cs:line 149

[01:18:02.170] [EROR] Xunkong.Desktop.Pages.TravelNotesPage+<InitializeDataAsync>d__37.InitializeDataAsync
初始化旅行札记页面
System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。 (127.0.0.1:5755)
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError, CancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs, ValueTask, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String, Int32, HttpRequestMessage, Boolean, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String, Int32, HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage, CancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetTravelNotesSummaryAsync(GenshinRoleInfo role, Int32 month, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetTravelNotesSummaryAsync(GenshinRoleInfo role, Int32 month) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 358
   at Xunkong.Desktop.Pages.TravelNotesPage.InitializeDataAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\TravelNotesPage.xaml.cs:line 149

### 备注

一开始是挂梯子的，出现“提交参数有误 (-2)”错误，关闭梯子后变成了“由于目标计算机积极拒绝，无法连接。 (127.0.0.1:5755)”，且重启寻空后（未开梯子）变回“提交参数有误 (-2)”。

**Comment by Scighost** [comment]
很正常，月初凌晨会出现这种错误，现在已经没问题了。
