### ISSUE TITLE
祈愿记录导入功能-保存按钮的功能错误

### ISSUE THREAD

**Issue by Fthrepublic** [xunkong/xunkong#451]
### 问题描述

导入后，点击【保存】按钮，弹出【所选项将被删除】提示。
此时直接退出祈愿界面会白屏卡死。

### 复现步骤

将祈愿记录拖入导入导出界面，去保存。

### 截图

![image](https://user-images.githubusercontent.com/66349171/227108040-38fde629-dd28-498f-8baf-922c4aab1936.png)
![image](https://user-images.githubusercontent.com/66349171/227107786-43aa0493-87ff-43eb-a06c-7bfe75e778ed.png)

### 系统版本

22H2 22624.1465

### 寻空版本

1.3.3.0

### 日志

[12:11:49.444] [INFO] 
寻空 1.3.3.0
778A4AA175F9151846BA520E64788C17
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.3.3.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[12:11:49.449] [EROR] Xunkong.Desktop.Services.InvokeService+<CheckTransformerReachedAndHomeCoinFullAsync>d__1.CheckTransformerReachedAndHomeCoinFullAsync
检查洞天宝钱和参量质变仪 - Uid 192526353
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetDailyNoteAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetDailyNoteAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 351
   at Xunkong.Desktop.Services.InvokeService.CheckTransformerReachedAndHomeCoinFullAsync(Boolean sendInAppNotification) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\InvokeService.cs:line 82

**Comment by Scighost** [comment]
导入时只需要拖入文件就行，那个保存键是删除所选记录用的。
