### ISSUE TITLE
SQLite 数据库文件损坏

### ISSUE THREAD

**Issue by AmberWho** [xunkong/xunkong#453]
### 问题描述

报错“**SqliteException** SQLite Error 11: 'database disk image is malformed'.”
除了养成计划之外的用户信息全部丢失。
在正常运行和报错之间只有过一次网络运营商断网，此外只进行了关机-开机的操作，重装软件未解决。

### 复现步骤

点击我的角色
或者
添加账号-网页登录-完成登录后点击对勾导入Cookie

### 截图

![screenshot0324](https://user-images.githubusercontent.com/68289066/227615266-8a00df15-9840-45d4-bcb8-c090cee88dd5.png)
![screeshot0324-2](https://user-images.githubusercontent.com/68289066/227615281-51603359-bb13-45f4-85ca-9d38d08db8f7.png)

### 系统版本

Windows 10 21H2

### 寻空版本

1.3.3.0

### 日志

[14:42:07.055] [INFO] 
寻空 1.3.3.0
D42BB2AD8ED00BA92A4085188B19D738
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.3.3.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[14:42:07.057] [EROR] Xunkong.Desktop.Pages.MainPage.RefreshAllAcount
获取所有账号信息
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1066
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1187
   at Dapper.SqlMapper.QueryFirstOrDefault[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 774
   at Xunkong.Desktop.Helpers.DatabaseProvider.Initialize() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 55
   at Xunkong.Desktop.Helpers.DatabaseProvider.CreateConnection() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 72
   at Xunkong.Desktop.Services.HoyolabService.GetLastSelectedOrFirstHoyolabUserInfo() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 31
   at Xunkong.Desktop.Pages.MainPage.RefreshAllAcount() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 445

[14:42:07.073] [EROR] Xunkong.Desktop.Pages.MainPage+<<RefreshAllAcount>b__33_0>d.RefreshAllAcount
刷新所有账号信息或签到
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1066
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1187
   at Dapper.SqlMapper.QueryFirstOrDefault[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 774
   at Xunkong.Desktop.Helpers.DatabaseProvider.Initialize() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 55
   at Xunkong.Desktop.Helpers.DatabaseProvider.CreateConnection() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 72
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoList() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 65
   at Xunkong.Desktop.Services.HoyolabService.UpdateAllAccountsAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 110
   at Xunkong.Desktop.Pages.MainPage.<RefreshAllAcount>b__33_0() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 457

[14:42:07.182] [EROR] Xunkong.Desktop.Pages.HomePage+<GetDailyNotesAsync>d__26.GetDailyNotesAsync
实时便笺
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1066
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1187
   at Dapper.SqlMapper.QueryFirstOrDefault[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 774
   at Xunkong.Desktop.Helpers.DatabaseProvider.Initialize() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 55
   at Xunkong.Desktop.Helpers.DatabaseProvider.CreateConnection() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 72
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoList() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 65
   at Xunkong.Desktop.Pages.HomePage.GetDailyNotesAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\HomePage.xaml.cs:line 567

[14:42:07.184] [EROR] Xunkong.Desktop.Pages.HomePage.LoadGameAccounts
--->
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1066
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1187
   at Dapper.SqlMapper.QueryFirstOrDefault[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 774
   at Xunkong.Desktop.Helpers.DatabaseProvider.Initialize() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 55
   at Xunkong.Desktop.Helpers.DatabaseProvider.CreateConnection() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 72
   at Xunkong.Desktop.Services.GameAccountService.GetGameAccountsFromDatabase() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\GameAccountService.cs:line 76
   at Xunkong.Desktop.Pages.HomePage.LoadGameAccounts() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\HomePage.xaml.cs:line 987

[14:42:07.708] [EROR] Xunkong.Desktop.Pages.MainPage+<InitializeNavigationWebToolItem>d__31.InitializeNavigationWebToolItem
加载网页小工具
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1066
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1187
   at Dapper.SqlMapper.QueryFirstOrDefault[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 774
   at Xunkong.Desktop.Helpers.DatabaseProvider.Initialize() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 55
   at Xunkong.Desktop.Helpers.DatabaseProvider.CreateConnection() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 72
   at Xunkong.Desktop.Pages.MainPage.<>c__DisplayClass31_0.<InitializeNavigationWebToolItem>b__1() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 388
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Xunkong.Desktop.Pages.MainPage.InitializeNavigationWebToolItem(Boolean delay) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 386

[14:42:12.339] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2.LoadCharacterInfos
--->
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1066
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1187
   at Dapper.SqlMapper.QueryFirstOrDefault[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 774
   at Xunkong.Desktop.Helpers.DatabaseProvider.Initialize() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 55
   at Xunkong.Desktop.Helpers.DatabaseProvider.CreateConnection() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 72
   at Xunkong.Desktop.Services.HoyolabService.GetLastSelectedOrFirstGenshinRoleInfo() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 48
   at Xunkong.Desktop.Pages.CharacterInfoPage2.LoadCharacterInfos(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 57

[14:42:44.848] [EROR] Xunkong.Desktop.Pages.LoginPage+<FinishAndAddCookie>d__9.FinishAndAddCookie
添加 Cookie
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1066
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1187
   at Dapper.SqlMapper.QueryFirstOrDefault[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 774
   at Xunkong.Desktop.Helpers.DatabaseProvider.Initialize() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 55
   at Xunkong.Desktop.Helpers.DatabaseProvider.CreateConnection() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 72
   at Xunkong.Desktop.Services.HoyolabService.GetHoyolabUserInfoAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 81
   at Xunkong.Desktop.Pages.MainPage.AddCookieAsync(String cookie) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 649
   at Xunkong.Desktop.Pages.LoginPage.FinishAndAddCookie() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\LoginPage.xaml.cs:line 154

[14:49:57.834] [EROR] Xunkong.Desktop.Services.BackupService.AutoBackupDatabase
自动备份数据库
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1066
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1187
   at Dapper.SqlMapper.QueryFirstOrDefault[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 774
   at Xunkong.Desktop.Helpers.DatabaseProvider.Initialize() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 55
   at Xunkong.Desktop.Helpers.DatabaseProvider.CreateConnection() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Helpers\DatabaseProvider.cs:line 72
   at Xunkong.Desktop.Services.BackupService.AutoBackupDatabase() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\BackupSerivce.cs:line 101

**Comment by AmberWho** [comment]
卸载并手动删除了Database文件夹重新安装就可以正常使用了，之前没有检查卸载是否删除了文件

**Comment by Scighost** [comment]
你应该在 `Xunkong\Backup\Database` 里找到最新的备份替换 `Database` 里的文件。
