### ISSUE TITLE
更新1.3.7后无边框模式失效

### ISSUE THREAD

**Issue by Karunari-luoling** [xunkong/xunkong#482]
### 问题描述

更新1.3.7后无边框模式失效，卸载重新安装依然不能生效，帧率解锁正常生效
[![p9P8avj.png](https://s1.ax1x.com/2023/04/17/p9P8avj.png)](https://imgse.com/i/p9P8avj)

### 复现步骤

启动游戏后寻空是在游戏界面的上面的（按住win键，无边框模式是生效的）[![p9P8Bbq.png](https://s1.ax1x.com/2023/04/17/p9P8Bbq.png)](https://imgse.com/i/p9P8Bbq)
点击游戏后，无边框模式失效，按住win键游戏会自动最小化

### 系统版本

Windows11专业工作站版 22H2 22621.1555

### 寻空版本

1.3.7.0

### 日志

[22:21:38.887] [INFO] 
寻空 1.3.7.0
23E1E716D21B27E094D29260A261C555
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.3.7.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[22:21:38.888] [EROR] Xunkong.Desktop.Services.InvokeService+<CheckTransformerReachedAndHomeCoinFullAsync>d__2.CheckTransformerReachedAndHomeCoinFullAsync
检查洞天宝钱和参量质变仪 - Uid 20870****
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetDailyNoteAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetDailyNoteAsync(GenshinRoleInfo role, Boolean disableCache) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 369
   at Xunkong.Desktop.Services.InvokeService.CheckTransformerReachedAndHomeCoinFullAsync(Boolean sendInAppNotification) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\InvokeService.cs:line 134

[22:21:39.019] [EROR] Xunkong.Desktop.Services.InvokeService+<CheckTransformerReachedAndHomeCoinFullAsync>d__2.CheckTransformerReachedAndHomeCoinFullAsync
检查洞天宝钱和参量质变仪 - Uid 2698*****
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetDailyNoteAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetDailyNoteAsync(GenshinRoleInfo role, Boolean disableCache) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 369
   at Xunkong.Desktop.Services.InvokeService.CheckTransformerReachedAndHomeCoinFullAsync(Boolean sendInAppNotification) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\InvokeService.cs:line 134

**Comment by Scighost** [comment]
游戏进入了全屏独占模式后按 `Win` 会最小化，按 `Alt+Enter` 可在全屏独占和窗口模式间切换。
