### ISSUE TITLE
无法获取“我的角色”信息

### ISSUE THREAD

**Issue by qiuqiu-2** [xunkong/xunkong#506]
### 问题描述

点击刷新以后一直提示“HoyolabException 请先登录（-100）",但问题是我已经登录了

### 复现步骤

点击“我的角色”的刷新键就会这样

### 截图

![image](https://github.com/xunkong/xunkong/assets/67945933/d6568537-202a-448c-949d-a951f898ad22)

### 系统版本

Windows 10 22H2

### 寻空版本

1.3.8.0

### 日志

[12:52:08.095] [INFO] 
寻空 1.3.8.0
6BB579073B63638066910868A50E2F4F
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.3.8.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[12:52:08.097] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException: 请先登录 (-100)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarSkillLevelAsync(GenshinRoleInfo role, Int32 characterId, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.<>c__DisplayClass35_0.<<GetCharacterInfosAsync>b__0>d.MoveNext() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 497
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 495
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[12:52:10.682] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException: 请先登录 (-100)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarSkillLevelAsync(GenshinRoleInfo role, Int32 characterId, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.<>c__DisplayClass35_0.<<GetCharacterInfosAsync>b__0>d.MoveNext() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 497
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 495
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[12:52:22.597] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException: 请先登录 (-100)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarSkillLevelAsync(GenshinRoleInfo role, Int32 characterId, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.<>c__DisplayClass35_0.<<GetCharacterInfosAsync>b__0>d.MoveNext() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 605
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 495
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[12:52:44.819] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException: 请先登录 (-100)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarSkillLevelAsync(GenshinRoleInfo role, Int32 characterId, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.<>c__DisplayClass35_0.<<GetCharacterInfosAsync>b__0>d.MoveNext() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 605
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 495
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[12:54:54.548] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException: 请先登录 (-100)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarSkillLevelAsync(GenshinRoleInfo role, Int32 characterId, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.<>c__DisplayClass35_0.<<GetCharacterInfosAsync>b__0>d.MoveNext() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 605
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 495
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[12:55:15.828] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException: 请先登录 (-100)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarSkillLevelAsync(GenshinRoleInfo role, Int32 characterId, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.<>c__DisplayClass35_0.<<GetCharacterInfosAsync>b__0>d.MoveNext() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 605
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 495
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[12:55:24.479] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException: 请先登录 (-100)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarSkillLevelAsync(GenshinRoleInfo role, Int32 characterId, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.<>c__DisplayClass35_0.<<GetCharacterInfosAsync>b__0>d.MoveNext() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 605
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 495
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[12:55:33.658] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException: 请先登录 (-100)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarSkillLevelAsync(GenshinRoleInfo role, Int32 characterId, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.<>c__DisplayClass35_0.<<GetCharacterInfosAsync>b__0>d.MoveNext() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 605
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 495
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[12:56:00.183] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException: 请先登录 (-100)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarSkillLevelAsync(GenshinRoleInfo role, Int32 characterId, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.<>c__DisplayClass35_0.<<GetCharacterInfosAsync>b__0>d.MoveNext() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 605
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 495
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

**Comment by wnight9527** [comment]
我也是这个问题，估计是米游社接口出了问题吧
