### ISSUE TITLE
1034错误

### ISSUE THREAD

**Issue by Nightingale123** [xunkong/xunkong#539]
### 问题描述

无法更新米游社的角色信息等，只能删除账号重新登陆才行。HoyolabException（1034）
也没有其他验证登陆的办法

### 复现步骤

从很久以前到现在一直都是这样

### 系统版本

Windows 10 22H2

### 寻空版本

1.4.0.0最新版

### 日志

[23:32:44.547] [INFO] 
寻空 1.4.0.0
029F3412BD044A27969359C35B24AE53
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.4.0.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[23:32:44.551] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarDetailsAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 493
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[23:32:46.116] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarDetailsAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 493
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[23:32:49.515] [EROR] Xunkong.Desktop.Pages.MainPage+<GetGameRecordAsync>d__39.GetGameRecordAsync
--->
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetGameRecordSummaryAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetGameRecordSummaryAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 339
   at Xunkong.Desktop.Pages.MainPage.GetGameRecordAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 643

[23:33:21.599] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarDetailsAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 493
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[23:34:06.303] [EROR] Xunkong.Desktop.Pages.MainPage+<<GetGenshinData>b__33_0>d.GetGenshinData
获取原神数据
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: 由于线程退出或应用程序请求，已中止 I/O 操作。.
 ---> System.Net.Sockets.SocketException (995): 由于线程退出或应用程序请求，已中止 I/O 操作。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Compression.BrotliStream.<ReadAsync>g__Core|24_0(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsync>g__Core|27_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Xunkong.ApiClient.XunkongApiClient.CommonGetAsync[T](String url)
   at Xunkong.ApiClient.XunkongApiClient.GetAllGenshinDataAsync()
   at Xunkong.Desktop.Services.XunkongApiService.GetAllGenshinDataFromServerAsync(Boolean force) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\XunkongApiService.cs:line 209
   at Xunkong.Desktop.Pages.MainPage.<GetGenshinData>b__33_0() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\MainPage.xaml.cs:line 502

[23:36:07.258] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarDetailsAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 493
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[23:39:03.792] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarDetailsAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 493
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[23:39:09.773] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarDetailsAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 493
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[23:39:22.877] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarDetailsAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 493
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

[23:39:41.345] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarDetailsAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 493
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 95

### 备注

我认为这是广泛存在的问题，很影响使用

**Comment by supersux** [comment]
你好，我本人也遇到了此问题，经过调研，发现这个问题是米游社风控导致的，解决方法如下
`step1`  找到主页中的实时便笺
> ![1702646399749](https://cdn.jsdelivr.net/gh/supersux/pichub@main/1702646399749.webp)
如果没有实时便笺，建议进行如下操作打开
设置 -> 功能 -> 主页功能 -> 实时便签开关（开）
![1702646695750](https://cdn.jsdelivr.net/gh/supersux/pichub@main/1702646695750.webp)

`step2`：验证账号即可，验证成功后如下
![1702646633616](https://cdn.jsdelivr.net/gh/supersux/pichub@main/1702646633616.webp)

`step3`: 验证成功后在我的角色或深境螺旋刷新数据
