### ISSUE TITLE
深渊信息获取失败

### ISSUE THREAD

**Issue by AetherPower** [xunkong/xunkong#551]
### 问题描述

点击刷新数据后会出现报错 hoyolab exception 1034

### 复现步骤

深境螺旋-刷新数据

### 截图

![1](https://github.com/xunkong/xunkong/assets/68303454/c0cf37aa-d412-4293-a317-19267bd3c35b)

### 系统版本

windows 10 22H2

### 寻空版本

1.4.2.0侧载

### 日志

[23:41:27.913] [INFO] 
寻空 侧载版 1.4.2.0
9F5CB8676FFBF800494E8ED05F68CDE9
"C:\Program Files\WindowsApps\Xunkong.Desktop.Package_1.4.2.0_x64__fyamk49073ha2\Xunkong.Desktop\Xunkong.Desktop.dll" RefreshTile

[23:41:27.914] [EROR] Xunkong.Desktop.Services.InvokeService+<RefreshDailyNoteTilesAsync>d__0.RefreshDailyNoteTilesAsync
刷新磁贴 - Uid 102330082
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetDailyNoteAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetDailyNoteAsync(GenshinRoleInfo role, Boolean disableCache) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 369
   at Xunkong.Desktop.Services.InvokeService.RefreshDailyNoteTilesAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\InvokeService.cs:line 33

**Comment by xiaoshazizizizizizizi** [comment]
我的角色这一栏也是

**Comment by AetherPower** [comment]
我发现了，去验证账号点验证码就好了。。。

**Comment by wl4318** [comment]
> 我发现了，去验证账号点验证码就好了。。。

我也有这个问题，在哪里验证账号呀
