### ISSUE TITLE
全部功能都异常

### ISSUE THREAD

**Issue by zhang121z** [xunkong/xunkong#555]
### 问题描述

全部功能都异常。
一直显示：“SqliteException”
Error 14：“unable to open db file”

### 复现步骤

进入就是如此。不需要额外操作

### 截图

![image](https://github.com/xunkong/xunkong/assets/50909200/21baa821-9660-4046-b316-ad3a2bcd3a0b)
![image](https://github.com/xunkong/xunkong/assets/50909200/35a22270-5c46-4f4d-b867-33d12e5b2962)

### 系统版本

Windows 11 专业版 22H2 22621.2428

### 寻空版本

寻空 侧载版 1.4.2.0

### 日志

 
[15:49:15.118] [INF] 
2023-10-10T15:49:15.1160214+08:00
Xunkong Desktop Log Message
App Name: 寻空
App Version: 0.2.0.1
OS Version: Microsoft Windows NT 10.0.22621.0
Device Id: 57252ECBA22123992830570839024103
Data Path: C:\Users\zhang\Documents\Xunkong
WebView2 Version: 117.0.2045.60
Command Line: "C:\Program Files\WindowsApps\Xunkong.Desktop_0.2.0.1_x64__fyamk49073ha2\Xunkong.Desktop\Xunkong.Desktop.dll"

 
[15:49:16.138] [INF] 
Last version is 0.2.0.1.
 
[15:49:16.138] [INF] 
Last version is equal with or bigger than current version, don't need to migrate database.
 
[15:49:25.172] [DBG] Xunkong.Desktop.ViewModels.UserPanelViewModel
Initlize User Panel.
 
[15:49:25.273] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectUserInfoUid", value 4915235
 
[15:49:25.319] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectGameRoleUid", value 101917361
 
[15:49:25.360] [DBG] Xunkong.Desktop.ViewModels.UserPanelViewModel
Start refresh all hoyolab and genshin user info.
 
[15:49:26.397] [ERR] Xunkong.Desktop.ViewModels.WindowRootViewModel
Initialize and get recommend wallpaper.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Xunkong.Core.XunkongApi.XunkongApiClient.CommonGetAsync[T](String url)
   at Xunkong.Core.XunkongApi.XunkongApiClient.GetRecommendWallpaperAsync()
   at Xunkong.Desktop.Services.XunkongApiService.GetRecommendWallpaperAsync()
   at Xunkong.Desktop.ViewModels.WindowRootViewModel.InitializeBackgroundWallpaperAsync()
 
[15:49:26.655] [VRB] Xunkong.Desktop.Services.UserSettingService
Query UserSetting by key "LastSelectGameRoleUid" with value "101917361"
 
[15:49:26.666] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectUserInfoUid", value 4915235
 
[15:49:26.669] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectGameRoleUid", value 101917361
 
[15:49:26.670] [DBG] Xunkong.Desktop.ViewModels.UserPanelViewModel
Finish refresh all hoyolab and genshin user info.
 
[15:49:27.439] [VRB] Xunkong.Desktop.Services.UserSettingService
Query UserSetting by key "SignInAllAccountsWhenStartUpApplication" with value "True"
 
[15:49:28.602] [WRN] Microsoft.EntityFrameworkCore.Model.Validation
The property '"WishEventInfo"."Rank4UpItems"' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
 
[15:49:28.602] [WRN] Microsoft.EntityFrameworkCore.Model.Validation
The property '"WishEventInfo"."Rank5UpItems"' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
 
[15:49:29.371] [ERR] Xunkong.Desktop.ViewModels.WindowRootViewModel
Error when check version update startup in CheckVersionUpdateAsync
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Xunkong.Core.XunkongApi.XunkongApiClient.CommonGetAsync[T](String url)
   at Xunkong.Core.XunkongApi.XunkongApiClient.CheckDesktopUpdateAsync(ChannelType channel)
   at Xunkong.Desktop.Services.XunkongApiService.CheckUpdateAsync(ChannelType channel)
   at Xunkong.Desktop.ViewModels.WindowRootViewModel.CheckVersionUpdateAsync()
 
[15:49:29.407] [INF] Xunkong.Desktop.Views.WindowRootView
Navigate to "SettingPage"
 
[15:49:29.772] [ERR] Xunkong.Desktop.Views.WindowRootView
Error in "CheckNotifications"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Xunkong.Core.XunkongApi.XunkongApiClient.CommonGetAsync[T](String url)
   at Xunkong.Core.XunkongApi.XunkongApiClient.GetNotificationsAsync[T](ChannelType channel, Version version, Int32 lastId)
   at Xunkong.Desktop.Services.XunkongApiService.GetNotificationsAsync(ChannelType channel, Version version)
   at Xunkong.Desktop.Views.WindowRootView.<CheckNotifications>b__20_0()
 
[15:49:30.185] [ERR] Xunkong.Desktop.ViewModels.WindowRootViewModel
SignInAllAccountsAsync
Xunkong.Core.Hoyolab.HoyolabException: 尚未登录 (-100)
   at Xunkong.Core.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request)
   at Xunkong.Core.Hoyolab.HoyolabClient.GetSignInInfoAsync(UserGameRoleInfo role)
   at Xunkong.Desktop.Services.HoyolabService.SignInAsync(UserGameRoleInfo role)
   at Xunkong.Desktop.ViewModels.WindowRootViewModel.SignInAllAccountsAsync()
 
[15:49:30.327] [VRB] Xunkong.Desktop.Services.UserSettingService
Query UserSetting by key "SignInAllAccountsWhenStartUpApplication" with value "True"
 
[15:49:30.328] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "SignInAllAccountsWhenStartUpApplication", value True
 
[15:49:30.333] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "SignInAllAccountsWhenStartUpApplication", value True
 
[15:49:36.435] [ERR] Xunkong.Desktop.ViewModels.SettingViewModel
Error in CheckUpdateAsync
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Xunkong.Core.XunkongApi.XunkongApiClient.CommonGetAsync[T](String url)
   at Xunkong.Core.XunkongApi.XunkongApiClient.CheckDesktopUpdateAsync(ChannelType channel)
   at Xunkong.Desktop.Services.XunkongApiService.CheckUpdateAsync(ChannelType channel)
   at Xunkong.Desktop.ViewModels.SettingViewModel.CheckUpdateAsync()
 
[15:49:46.263] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "SignInAllAccountsWhenStartUpApplication", value False
 
[15:49:51.406] [INF] Xunkong.Desktop.Views.WindowRootView
Navigate to "WishlogSummaryPage"
 
[15:49:52.107] [VRB] Xunkong.Desktop.Services.UserSettingService
Query UserSetting by key "LastSelectedUidInWishlogSummaryPage" with value "100623239"
 
[15:49:52.131] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectedUidInWishlogSummaryPage", value 100623239
 
[15:49:54.833] [INF] Xunkong.Desktop.MainWindow
MainWindow closed.

**Comment by YvetteVv** [comment]
mark一下 一样的问题

**Comment by zhang121z** [comment]
我更换商店版之后已经好了

**Comment by zhang121z** [comment]
> mark一下 一样的问题
卸载侧载版，将数据库迁移到新安装的商店版可以解决
