### ISSUE TITLE
刷新我的角色出现HoyolabException  (1034)问题

### ISSUE THREAD

**Issue by GLWB** [xunkong/xunkong#556]
### 问题描述

刷新我的角色出现HoyolabException  (1034)问题

### 复现步骤

1，点击左侧栏目中的“我的角色”
2，点击右上角的“获取数据“
即可复现问题

不知道能否解决……

### 截图

<img width="960" alt="1" src="https://github.com/xunkong/xunkong/assets/115604342/115a157b-826b-44a9-a1f3-2798f24040ae">

### 系统版本

Windows 11 家庭中文版 22H2

### 寻空版本

1.4.2.0

### 日志

[16:25:55.339] [INFO] 
寻空 1.4.2.0
FDB51D0B81BC2205B9391A6A9CCC3203
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.4.2.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[16:25:55.340] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarDetailsAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 493
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 94

[16:27:52.222] [EROR] Xunkong.Desktop.Pages.CharacterInfoPage2+<GetCharacterInfosAsync>d__6.GetCharacterInfosAsync
--->
Xunkong.Hoyolab.HoyolabException:  (1034)
   at Xunkong.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request, Nullable`1 cancellationToken)
   at Xunkong.Hoyolab.HoyolabClient.GetAvatarDetailsAsync(GenshinRoleInfo role, Nullable`1 cancellationToken)
   at Xunkong.Desktop.Services.HoyolabService.GetCharacterInfosAsync(GenshinRoleInfo role) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\HoyolabService.cs:line 493
   at Xunkong.Desktop.Pages.CharacterInfoPage2.GetCharacterInfosAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\CharacterInfoPage2.xaml.cs:line 94

**Comment by MafiaAce** [comment]
最近我也这样  刷新旅行札记、深渊记录等需要同步的数据都这样  每次都要重新登陆

**Comment by Klamist** [comment]
应该是触发了米游社验证码，这个starward里已经做了手动验证窗口了，xunkong莫非还没。

**Comment by HyBoxwood** [comment]
同问题，删除账号重新添加也不会刷新。
![QQ截图20231027101900](https://github.com/xunkong/xunkong/assets/87700780/754929c5-7287-4bed-925b-92c6863ab50a)
![QQ截图20231027101842](https://github.com/xunkong/xunkong/assets/87700780/5a8bb5a1-8057-4fa2-86dc-647bad581456)

**Comment by supersux** [comment]
你好，我本人也遇到了此问题，经过调研，发现这个问题是米游社风控导致的，解决方法如下
`step1`  找到主页中的实时便笺
> ![1702646399749](https://cdn.jsdelivr.net/gh/supersux/pichub@main/1702646399749.webp)
如果没有实时便笺，建议进行如下操作打开
设置 -> 功能 -> 主页功能 -> 实时便签开关（开）
![1702646695750](https://cdn.jsdelivr.net/gh/supersux/pichub@main/1702646695750.webp)

`step2`：验证账号即可，验证成功后如下
![1702646633616](https://cdn.jsdelivr.net/gh/supersux/pichub@main/1702646633616.webp)

`step3`: 验证成功后在我的角色或深境螺旋刷新数据

**Comment by HyBoxwood** [comment]
> 你好，我本人也遇到了此问题，经过调研，发现这个问题是米游社风控导致的，解决方法如下 `step1` 找到主页中的实时便笺
> 
> > ![1702646399749](https://camo.githubusercontent.com/f9eb408617f4844213dbb82301c5137f0efa4ca99ff3fee99070b511b993bca7/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f73757065727375782f706963687562406d61696e2f313730323634363339393734392e77656270)
> > 如果没有实时便笺，建议进行如下操作打开
> > 设置 -> 功能 -> 主页功能 -> 实时便签开关（开）
> > ![1702646695750](https://camo.githubusercontent.com/2d1510cf6b475e94cb2aeea7bb43d6724c685220421cd09e345ff376f7f29950/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f73757065727375782f706963687562406d61696e2f313730323634363639353735302e77656270)
> 
> `step2`：验证账号即可，验证成功后如下 ![1702646633616](https://camo.githubusercontent.com/7ab7201b710b7708d9d790f4531e9bce0d6735ba4d392256a018b344ef501dce/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f73757065727375782f706963687562406d61696e2f313730323634363633333631362e77656270)
> 
> `step3`: 验证成功后在我的角色或深境螺旋刷新数据

不太懂这样的操作是怎么解除米游社风控的，本人未实现。

![QQ截图20231216070643](https://github.com/xunkong/xunkong/assets/87700780/ecb2d1a6-64cb-4daf-b0ff-9f15f906260c)

![QQ截图20231216070708](https://github.com/xunkong/xunkong/assets/87700780/d2f4e4b4-ad41-4926-992d-bd4e178dc9ef)

![QQ截图20231216070721](https://github.com/xunkong/xunkong/assets/87700780/c4b7d696-f2b6-4e31-8b2d-65e5620f09df)

![QQ截图20231216070734](https://github.com/xunkong/xunkong/assets/87700780/7a8df9a8-ba43-4820-b8f7-f05e02738082)

隔壁[Snap Hutao](https://github.com/DGP-Studio/Snap.Hutao/)是可以正常刷新的，并且是一次登录就可以了。
虽然我几乎不用它但是它确实能用，喜欢用寻空但是寻空用不了。

![QQ截图20231216071159](https://github.com/xunkong/xunkong/assets/87700780/80191eb6-ca2f-432b-ae8f-dc1b10a324f2)

**Comment by supersux** [comment]
> > 你好，我本人也遇到了此问题，经过调研，发现这个问题是米游社风控导致的，解决方法如下 `step1` 找到主页中的实时便笺
> > > ![1702646399749](https://camo.githubusercontent.com/f9eb408617f4844213dbb82301c5137f0efa4ca99ff3fee99070b511b993bca7/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f73757065727375782f706963687562406d61696e2f313730323634363339393734392e77656270)
> > > 如果没有实时便笺，建议进行如下操作打开
> > > 设置 -> 功能 -> 主页功能 -> 实时便签开关（开）
> > > ![1702646695750](https://camo.githubusercontent.com/2d1510cf6b475e94cb2aeea7bb43d6724c685220421cd09e345ff376f7f29950/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f73757065727375782f706963687562406d61696e2f313730323634363639353735302e77656270)
> > 
> > 
> > `step2`：验证账号即可，验证成功后如下 ![1702646633616](https://camo.githubusercontent.com/7ab7201b710b7708d9d790f4531e9bce0d6735ba4d392256a018b344ef501dce/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f73757065727375782f706963687562406d61696e2f313730323634363633333631362e77656270)
> > `step3`: 验证成功后在我的角色或深境螺旋刷新数据
> 
> 不太懂这样的操作是怎么解除米游社风控的，本人未实现。
> 
> ![QQ截图20231216070643](https://private-user-images.githubusercontent.com/87700780/290953533-ecb2d1a6-64cb-4daf-b0ff-9f15f906260c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDExMTAsIm5iZiI6MTcwMjcwMDgxMCwicGF0aCI6Ii84NzcwMDc4MC8yOTA5NTM1MzMtZWNiMmQxYTYtNjRjYi00ZGFmLWIwZmYtOWYxNWY5MDYyNjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA0MjY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NDEzNzM1MGQyMDY4ZjQzMDFmZWY0MThkZDk2MzQ2NjYzZGY1ZjNhZjBiNjE4NWE4ZTVkYWY5MTJhMzVkZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lvCV_extLdF9NzTLkKkxhfrZcgvXX_U-LDxkKqqcvvQ)
> 
> ![QQ截图20231216070708](https://private-user-images.githubusercontent.com/87700780/290953536-d2f4e4b4-ad41-4926-992d-bd4e178dc9ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDExMTAsIm5iZiI6MTcwMjcwMDgxMCwicGF0aCI6Ii84NzcwMDc4MC8yOTA5NTM1MzYtZDJmNGU0YjQtYWQ0MS00OTI2LTk5MmQtYmQ0ZTE3OGRjOWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA0MjY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYzNkNjgxMzNmN2M4NGE0NjgxNmE5NmNmNWVkNGYwMWVkNTczNTA2ODA2OWYyY2EzMDlkOTY5MmY1MDMzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Am7hJHTvyv1zwAEchyfa5dzOywSkW2ihWR1TGi_m4wA)
> 
> ![QQ截图20231216070721](https://private-user-images.githubusercontent.com/87700780/290953545-c4b7d696-f2b6-4e31-8b2d-65e5620f09df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDExMTAsIm5iZiI6MTcwMjcwMDgxMCwicGF0aCI6Ii84NzcwMDc4MC8yOTA5NTM1NDUtYzRiN2Q2OTYtZjJiNi00ZTMxLThiMmQtNjVlNTYyMGYwOWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA0MjY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZDVmOGFlMmYzODRhMTE4ZjQ4ZmRmM2QzNWZhY2ZkMTU4MWQxNWZlNzUxZmZmY2RjODc5ZTAyZjAzM2M2OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dU3SwK4en67D25NpFnf1v2ZP4I2s07lG-hCMvx5K6Sg)
> 
> ![QQ截图20231216070734](https://private-user-images.githubusercontent.com/87700780/290953548-7a8df9a8-ba43-4820-b8f7-f05e02738082.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDExMTAsIm5iZiI6MTcwMjcwMDgxMCwicGF0aCI6Ii84NzcwMDc4MC8yOTA5NTM1NDgtN2E4ZGY5YTgtYmE0My00ODIwLWI4ZjctZjA1ZTAyNzM4MDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA0MjY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNDc4YzA3MDBjYzBlNGIyODMyOTQxNDk0Y2U0MmU3OGM1YTFkMTE2MDU3NDRlMWNkYzM2Nzg0ZDU5ZGEyMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MfON2U19m7KaJ9iMUNzPQ-vUKWTkqx0A1tRQaZQZuWg)
> 
> 隔壁[Snap Hutao](https://github.com/DGP-Studio/Snap.Hutao/)是可以正常刷新的，并且是一次登录就可以了。 虽然我几乎不用它但是它确实能用，喜欢用寻空但是寻空用不了。
> 
> ![QQ截图20231216071159](https://private-user-images.githubusercontent.com/87700780/290954101-80191eb6-ca2f-432b-ae8f-dc1b10a324f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MDExMTAsIm5iZiI6MTcwMjcwMDgxMCwicGF0aCI6Ii84NzcwMDc4MC8yOTA5NTQxMDEtODAxOTFlYjYtY2EyZi00MzJiLWFlOGYtZGMxYjEwYTMyNGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA0MjY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OGY1ZGFhYTJiMTJlNDQ1OWY4NzU0NDc2YmM1ZTdmMWNkN2U4Y2E0ODZlYzI2ZjM0ZWQwMDY4OWYwZjgxNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.og7Bl4MnOHsxsSxNSKioAabQYeAlgnmNPfscAYwCSg0)

很抱歉我本人没有出现这样的问题，不过在寻空的代码中并未出现对`5003`这个错误码的描述，大概率还是米游社服务器返回的代码，我在[胡桃工具的问题区域](https://hut.ao/zh/advanced/known-issue.html)找到了这个

![1702701497291](https://cdn.jsdelivr.net/gh/supersux/pichub@main/1702701497291.webp)
![1702701497293](https://cdn.jsdelivr.net/gh/supersux/pichub@main/1702701497293.webp)

所以推测可能是因为你本地同时使用了胡桃工具箱和寻空工具多次刷新便笺导致的，我的建议是两个都不再使用，转向隔壁的[Starward](https://github.com/Scighost/Starward)，界面非常漂亮，可以尝试使用一下
