### ISSUE TITLE
你的标题

### ISSUE THREAD

**Issue by anzhen9** [xunkong/xunkong#562]
### 问题描述

祈愿记录网址有变更，目前还未兼容

### 复现步骤

现网址https://public-operation-hk4e.mihoyo.com/gacha_info/api/getGachaLog，直接粘贴会报网址无效，改为原网址https://hk4e-api.mihoyo.com/event/gacha_info/api/getGachaLog后可以

### 截图

![image](https://github.com/xunkong/xunkong/assets/23622902/11a75a78-a48a-412f-8bd5-c5768e1d9c3a)

### 系统版本

windows 11 23H2

### 寻空版本

1.4.2.0

### 日志

[11:55:03.567] [INFO] 
寻空 1.4.2.0
BB2465C2C2E6C09B37A7D64888D9033D
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.4.2.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[11:55:03.568] [EROR] Xunkong.Desktop.Pages.WishlogSummaryPage2+<DownloadWishlogFromCloudCompletelyAsync>d__42.DownloadWishlogFromCloudCompletelyAsync
下载祈愿记录备份
System.IO.FileNotFoundException: 请重新获取祈愿记录网址
   at Xunkong.Desktop.Services.WishlogService.FindWishlogUrlFromLogFileAsync(Boolean isSea) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\WishlogService.cs:line 88
   at Xunkong.Desktop.Services.XunkongApiService.CheckWishlogUrlAsync(Int32 uid, IProgress`1 progress) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\XunkongApiService.cs:line 82
   at Xunkong.Desktop.Services.XunkongApiService.GetWishlogBackupListAsync(Int32 uid, IProgress`1 progress, Boolean getAll) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Services\XunkongApiService.cs:line 108
   at Xunkong.Desktop.Pages.WishlogSummaryPage2.DownloadWishlogFromCloudCompletelyAsync() in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\Pages\WishlogSummaryPage2.xaml.cs:line 1042

**Comment by jdy18** [comment]
请问这个网址在哪里修改？
