### ISSUE TITLE
旅行札记报错显示为空白

### ISSUE THREAD

**Issue by PurBlu** [xunkong/xunkong#96]
### 问题描述

点击旅行札记后无法查看之前所有的历史数据信息 
并提示`HoyolabException` 错误：提交参数有误(-2)
尝试点击`仅本月`与`近三月`获取记录按钮拉取数据时仍提示上述错误

### 复现步骤

```plain text
主界面点击旅行札记即提示 100%复现
```

### 截图

![image](https://user-images.githubusercontent.com/74239692/166115173-55ef3a52-1db7-4199-841a-20766356cbe8.png)

### 系统版本

Windows 11 Pro 21H2 22000.613

### 寻空版本

0.2.0.0

### 日志

```
[00:04:53.999] [INF] 
2022-05-01T00:04:53.9976503+08:00
Xunkong Desktop Log Message
App Name: 寻空
App Version: 0.2.0.0
OS Version: Microsoft Windows NT 10.0.22000.0
Device Id: 12882668352B388A9CE75FBFD0318BD1
Data Path: C:\Users\PureBlue\Documents\Xunkong
WebView2 Version: 100.0.1185.50
Command Line: "C:\Program Files\WindowsApps\Xunkong.Desktop_0.2.0.0_x64__fyamk49073ha2\Xunkong.Desktop\Xunkong.Desktop.dll"

 
[00:04:54.033] [INF] 
Last version is 0.2.0.0.
 
[00:04:54.033] [INF] 
Last version is equal with or bigger than current version, don't need to migrate database.
 
[00:04:55.390] [DBG] Xunkong.Desktop.ViewModels.UserPanelViewModel
Initlize User Panel.
 
[00:04:55.412] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectUserInfoUid", value 7512798
 
[00:04:55.434] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectGameRoleUid", value 100927523
 
[00:04:55.442] [DBG] Xunkong.Desktop.ViewModels.UserPanelViewModel
Start refresh all hoyolab and genshin user info.
 
[00:04:56.506] [INF] Xunkong.Desktop.MainWindow
Change background image:
https://file.xunkong.cc/wallpaper/[大眼睛眨巴眨眨] 优菈～～～ [94345171_p1].webp
 
[00:04:57.246] [VRB] Xunkong.Desktop.Services.UserSettingService
Query UserSetting by key "LastSelectGameRoleUid" with value "100927523"
 
[00:04:57.256] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectUserInfoUid", value 7512798
 
[00:04:57.257] [VRB] Xunkong.Desktop.Services.UserSettingService
Save UserSetting with key "LastSelectGameRoleUid", value 100927523
 
[00:04:57.257] [DBG] Xunkong.Desktop.ViewModels.UserPanelViewModel
Finish refresh all hoyolab and genshin user info.
 
[00:04:58.067] [WRN] Microsoft.EntityFrameworkCore.Model.Validation
The property '"WishEventInfo"."Rank4UpItems"' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
 
[00:04:58.067] [WRN] Microsoft.EntityFrameworkCore.Model.Validation
The property '"WishEventInfo"."Rank5UpItems"' is a collection or enumeration type with a value converter but with no value comparer. Set a value comparer to ensure the collection/enumeration elements are compared correctly.
 
[00:05:00.398] [INF] Xunkong.Desktop.Views.WindowRootView
Navigate to "TravelNotesPage"
 
[00:05:04.206] [ERR] Xunkong.Desktop.ViewModels.TravelNotesViewModel
Get travel record detail.
Xunkong.Core.Hoyolab.HoyolabException: 提交参数有误 (-2)
   at Xunkong.Core.Hoyolab.HoyolabClient.CommonSendAsync[T](HttpRequestMessage request)
   at Xunkong.Core.Hoyolab.HoyolabClient.GetTravelRecordSummaryAsync(UserGameRoleInfo role, Int32 month)
   at Xunkong.Desktop.Services.HoyolabService.GetTravelRecordSummaryAsync(UserGameRoleInfo role, Int32 month)
   at Xunkong.Desktop.ViewModels.TravelNotesViewModel.GetTravelRecordDetailAsync(Boolean onlyCurrentMonth)
 
[00:05:06.378] [INF] Xunkong.Desktop.Views.WindowRootView
Navigate to "CharacterInfoPage"
 
[00:05:06.971] [WRN] Microsoft.EntityFrameworkCore.Query
Compiling a query which loads related collections for more than one collection navigation, either via 'Include' or through projection, but no 'QuerySplittingBehavior' has been configured. By default, Entity Framework will use 'QuerySplittingBehavior.SingleQuery', which can potentially result in slow query performance. See https://go.microsoft.com/fwlink/?linkid=2134277 for more information. To identify the query that's triggering this warning call 'ConfigureWarnings(w => w.Throw(RelationalEventId.MultipleCollectionIncludeWarning))'.
 
[00:05:10.288] [INF] Xunkong.Desktop.Views.WindowRootView
Navigate to "TravelNotesPage"
 
[00:05:12.469] [INF] Xunkong.Desktop.MainWindow
MainWindow closed.

```
### 备注

Cookie的配置应是没有问题的，在浏览器中访问米游社登录态正常。实时便签和角色信息功能的工作也正常。手机米游社旅行札记可正常查阅所有数据。
另：4月30日晚使用该功能一切正常。
![O42}3FEOM5}NOY{4C${I1@R](https://user-images.githubusercontent.com/74239692/166115566-ca7558c0-115f-4847-8f3f-38d53dba8d94.jpg)
_4月30日使用截图_

**Comment by PurBlu** [comment]
5.1 3:02PM GMT+8
数据已可被正常读取 但出现 #98 所示错误
![image](https://user-images.githubusercontent.com/74239692/166135817-11fa3d1a-0c58-4e28-8e80-8d0e66673817.png)

**Comment by Scighost** [comment]
每月1日0点到4点，游戏内还是前一天，米游社的旅行者札记还没有新月份的数据，所以会出现提交参数错误。
等到早上就好了
